workspace = { members = ["ecs-proc-macros"] }
[package]
name = "custom_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecs-proc-macros = { path = "ecs-proc-macros" }